#!/bin/bash

# Currently supports:
# Crush Crush
# Realm Grinder
# Crusaders of The Lost Idols

# This script will do one of two things
# 1. Start clicking if a game is supported
# 2. Kill a previous clicker and exit

# Function to actually perform the click
function DoClick {
	# We check to see the active windows name
	if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Realm Grinder" ]]
	then
		while true
		do
			xdotool mousemove --sync --window "$windowid" 810 310 click --repeat 100 --delay 200 1 \
				mousemove --sync --window "$windowid" 800 300 click --repeat 100 --delay 200 1
		done
		exit
	elif [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Crush Crush" ]] # I run Crush Crush in 1920x1080 windowed
	then
		# We get the mouse location and then detect if it is near the date or flirt button
		mloc=$(xdotool getmouselocation | awk '{print $1}' | cut -d: -f2)
		echo "Original mouse location detected as: $mloc"
		if [[ $mloc -lt 950 ]]
		then
			xloc=580
			yloc=780
		else
			xloc=1180
			yloc=310
		fi

		while true
		do
			echo "xdotool mousemove --window $windowid $xloc $yloc click --repeat 10 1"
			xdotool mousemove --window "$windowid" $xloc $yloc click --repeat 10 1
		done
		exit
	elif [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Crusaders of The Lost Idols" ]]
	then
		while true
		do
			xdotool click --repeat 100 --delay 50 1
		done
		exit
	fi
}

# Send a keyup event for alt, since we might be holding that down
xdotool keyup alt

# We need to see if other clickers are running
killcount=0
for i in $(pidof -x my_clicker)
do
	if [[ $i == "$$" ]]
	then
		continue
	else
		killcount=$killcount+1
	fi

done

if [[ $killcount -gt 0 ]]
then
	for i in $(pidof -x my_clicker)
	do
		if [[ $i == "$$" ]]
		then
			continue
		else
			kill "$i"
		fi
	done

	killall xdotool
	killall my_clicker
else
	# If the active window is a supported one, go. Else, select one.
	windowid=$(xdotool getactivewindow)
	DoClick
	windowid=$(xdotool selectwindow)
	DoClick
	zenity --info --text "No clicker windows recognized" --title "Not Found"
	exit
fi
