#!/bin/bash

# Requires wmctrl and xdotool to be installed

# Check if Steam is already started
if pgrep -f steam.sh > /dev/null
then
	echo "Steam is already started. Since you lost it, we'll find it for you."
	steam &&
		exit 1
	exit
fi

# Fix for bug with Gnome Activities not allowing window switching with wmctrl
dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.hide();'

#steam steam://open/bigpicture &
steam &

sleep 1

# We wait for Steam network to come up
# Try 30 times, since we might wait for an update
for i in $(seq 1 30)
do
	if ! netstat -lp 2>&1 | grep -i steam > /dev/null
	then
		sleep 2
		echo "$i time waiting for Steam to start (Steam network ports not reserved)"
	fi
done

# Check if active window is steam
# Sleep and then try to raise it if it is not
# Try 3 times
for i in $(seq 1 3)
do
	# Raise Steam window and if fails we notify
	if [ ! "$(wmctrl -a Steam)" ]
	then
		echo "Steam not raised by our command, may already have focus"
	fi

	# Get active window and then see if it is Steam, otherwise loop again
	windowid=$(xdotool getactivewindow)
	activewindow="$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)"

	if [[ "$activewindow" == "Steam" ]]
	then
		echo "We found Steam, it is our active window"
		break # Steam is raised
	fi

	sleep 2
	echo "Steam Big Picture not available or not raised, attempt number $i"
done

# We'll get the active window again
windowid=$(xdotool getactivewindow)
activewindow="$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)"

# Send two Return keystrokes to Steam window ID
# One to skip intro, one to login first account
# Echo success or fail
if [[ "$activewindow" == "Steam" ]]
then
	xdotool key --window "$windowid" --delay 1000 --window "$windowid" Return key Return || 
		echo "xdotool exited oddly, did the window close?" && exit 1
	echo "Script done, you should be logged in!"
else
	echo "Something went wrong, skipping automatic login for Steam Big Picture!"
	echo "Our active window was $activewindow"
	exit 1
fi
