#!/bin/bash

# If Chrome is already running, raise it instead
if [[ "$(wmctrl -l | grep -o Chromium)" == "Chromium" ]]
then
	wmctrl -R Chromium
	echo Raised the Chromium window
	exit
fi

cd ~/Documents
if [[ "`ls -a | grep -o .chromiumprofile | head -n1`" == ".chromiumprofile" ]]
then
	echo Decrypting the directory
	gpg-zip -d .chromiumprofile
	if [[ $? -ne 0 ]]
	then
		echo Holy shit, something went wrong. Run the program again and type the password correctly? For a start? Maybe.
		zenity --no-wrap --error --text="Either a corrupted tarball or an incorrect password. Copy .chromiumprofile~ to .chromiumprofile to resolve." --title="The extraction has failed!"
		exit
	fi

#	echo type "y" to delete the encrypted source file
#	read gogo
#	if [[ "$gogo" == "y" ]]
#	then
#		rm -f .chromiumprofile
#		echo Deleted .chromiumprofile
#	fi
elif [[ "`ls -a | grep .hidden_chromium`" == ".hidden_chromium" ]]
then
	echo "Odd, the directory isn't encrypted, we'll just pretend we didn't see this."
	zenity --no-wrap --error --text="Somehow things were left unencrypted. Did the script exit normally?" --title="Warning!"
else
	echo The profile is missing, exiting to avoid damage.
	zenity --no-wrap --error --text="I can't find the profile. Someday I will have logic to make the profile here." --title="Profile Not Found!"
	exit
fi

chromium-browser --user-data-dir=.hidden_chromium/

mv .chromiumprofile .chromiumprofile~

echo "Okay, we exited. Let's hide the evidence."

# Delete the cache since it gets huge.
rm -rf .hidden_chromium/*/Cache/
rm -rf .hidden_chromium/*/Media\ Cache/
rm -rf .hidden_chromium/*/Service\ Worker/CacheStorage
rm -rf .hidden_chromium/ShaderCache
rm -rf .hidden_chromium/*/Application\ Cache

gpg-zip -c -o .chromiumprofile .hidden_chromium/

if [[ $? -ne 0 ]]
then
	echo "WTF, you messed up creating the file? We'll bail out of here so you don't break anything..."
	zenity --no-wrap --error --text="Creation of the encrypted tarball failed. User Action is Required to Recover." --title="Fatal Error!"
	exit
fi

rm -rf .hidden_chromium

zenity --info --text "Everything has been encrypted." --title "Finished"

#echo "type \"y\" to delete the unencrypted chromium profile (.hidden_chromium)"
#read stopstop
#if [[ "$stopstop" == "y" ]]
#then
#	rm -rf .hidden_chromium
#	echo Deleted .hidden_chromium
#fi
