#!/bin/bash

# If Chrome is already running, raise it instead
if [[ "$(wmctrl -l | grep -o Chromium)" == "Chromium" ]]
then
	wmctrl -R Chromium
	echo Raised the Chromium window
	exit
fi

cd ~/Documents || exit
if [ -f .chromiumprofile ]
then
	echo Decrypting the directory
	if ! gpg-zip -d .chromiumprofile
	then
		echo Holy shit, something went wrong. Run the program again and type the password correctly? For a start? Maybe.
		zenity --no-wrap --error --text="Either a corrupted tarball or an incorrect password. Copy .chromiumprofile~ to .chromiumprofile to resolve." --title="The extraction has failed!"
		exit
	fi

elif [ -f .hidden_chromium ]
then
	echo "Odd, the directory isn't encrypted, we'll just pretend we didn't see this."
	zenity --no-wrap --error --text="Somehow things were left unencrypted. Did the script exit normally?" --title="Warning!"
else
	echo No profile found. Creating a new Chromium profile.
fi

chromium-browser --user-data-dir=.hidden_chromium/

if [ -f .chromiumprofile ]
then
	mv .chromiumprofile .chromiumprofile~
fi

echo "Okay, we exited. Let's hide the evidence."

# Delete the cache since it gets huge.
rm -rf .hidden_chromium/*/Cache/
rm -rf .hidden_chromium/*/Media\ Cache/
rm -rf .hidden_chromium/*/Service\ Worker/CacheStorage
rm -rf .hidden_chromium/ShaderCache
rm -rf .hidden_chromium/*/Application\ Cache

gnome-terminal -- sh -c 'echo "Encrypting the Chromium profile" ; cd ~/Documents && gpg-zip -c -o .chromiumprofile .hidden_chromium/ && rm -rf .hidden_chromium'

if [ -f .hidden_chromium ]
then
	echo Unencrypted profile still present, something went wrong
	zenity --no-wrap --error --text="Chromium not encrypted! Something went wrong!" --title="Encryption failed!"
fi
