#!/bin/bash

# Assumes Steam starts in Big Picture
# Requires wmctrl and xdotool to be installed

steam &

# We wait for Steam network to come up
# Try 30 times, since we might wait for an update
for i in $(seq 1 30)
do
	if ! netstat -lp 2>&1 | grep -i steam > /dev/null
	then
		sleep 2
		echo "$i time waiting for Steam to start (Steam network ports not reserved)"
	fi
done

# Runs a script that uses a single monitor
my_xrandr hdmi_only

sleep 1

# Raise Steam window and then store which window is active
wmctrl -a Steam
sleep .5
windowid=$(xdotool getactivewindow)

# Check if active window is steam
# Sleep and then try to raise it if it is not
# Try 15 times
for i in $(seq 1 15)
do
	if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Steam" ]]
	then
		break # Steam is raised
	fi

	sleep 1
	echo "Steam window not available or not raised, try number $i"
	wmctrl -a Steam
	sleep .5
	windowid=$(xdotool getactivewindow)
done

# Sent two Return keystrokes to Steam window ID
# One to skip intro, one to login first account
# Echo success or fail
xdotool key --window "$windowid" --delay 1000 --window "$windowid" Return key Return && 
	echo "Script done, you should be logged in!" || 
	echo "Something went wrong, not doing anything!"
