#!/bin/bash

#Consider: sudo apt purge indicator-common

if [[ $1 != "--I-understand" ]]
then
	echo "This can cause damage if not run on a fresh system."
	echo "Ensure all commands should be run with Y answer!"
	echo "Append --I-understand to the command and run again!"
	exit
fi

# Turn off lock screen on resume
if [[ "$(dconf read /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend)" == "true" ]]
then
	echo "Setting the desktop to skip lock screen on resume."
	read -rp "Do you wish to Proceed? [Y/N] " answer
	if [[ "$answer" == "Y" ]]
	then
		echo "Changing the setting to false!"
		dconf write /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend false
		echo "The setting now reports: $(dconf read /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend)"
	else
		echo "No changes made!"
	fi
fi
