#!/bin/bash

case $1 in
  pre)
	killall steam

	# We wait for Steam to go away
	# Try 5 times, since we might be waiting for cloud sync
	for i in $(seq 1 5)
	do
		if ps aux | grep steam.sh | grep -v grep > /dev/null
		then
			sleep 2
			echo "$i time waiting for Steam to shutdown"
		fi
	done

	sleep 1

	killall -9 steam
    ;;
  post)
	sleep 1
	sudo -u bryan bash -c "export DISPLAY=:0 ; xdotool keydown Alt key s keyup Alt"
    ;;
esac
