#!/bin/bash

# Assumes Steam starts in Big Picture
# Requires wmctrl and xdotool to be installed

steam &

# We wait for Steam network to come up
while ! netstat -lp 2>&1 | grep -i steam > /dev/null
do
	sleep 2
	echo "Steam not started yet (Steam network ports not reserved)"
done

sleep 1

# Raise Steam window and then check what window is active
wmctrl -a Steam
sleep .5
windowid=$(xdotool getactivewindow)

# Check if active window is steam
# Sleep and then try to raise it if it is not
while [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" != "Steam" ]]
do
	sleep 1
	echo "Steam window not available or not raised"
	wmctrl -a Steam
	sleep .5
	windowid=$(xdotool getactivewindow)
done

# Send two Return keystrokes
# One to skip intro, one to login first account
xdotool key --delay 1000 Return key Return
