#!/bin/bash

# Assumes Steam starts in Big Picture
# Requires wmctrl and xdotool to be installed

steam &

# We wait for Steam network to come up
# Try 5 times
for i in $(seq 1 5)
do
	if ! netstat -lp 2>&1 | grep -i steam > /dev/null
	then
		sleep 2
		echo "Steam not started yet (Steam network ports not reserved)"
	fi
done

sleep 1

# Raise Steam window and then store which window is active
wmctrl -a Steam
sleep .5
windowid=$(xdotool getactivewindow)

# Check if active window is steam
# Sleep and then try to raise it if it is not
# Try 5 times
for i in $(seq 1 5)
do
	if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Steam" ]]
	then
		break # Steam is raised
	fi

	sleep 1
	echo "Steam window not available or not raised"
	wmctrl -a Steam
	sleep .5
	windowid=$(xdotool getactivewindow)
done

# Check if the active window is Steam
# If true, send two Return keystrokes
# One to skip intro, one to login first account
if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Steam" ]]
then
	xdotool key --window "$windowid" --delay 1000 --window "$windowid" Return key Return
	echo "Script done, you should be logged in!"
else
	echo "Something went wrong, not doing anything!"
fi
