#!/bin/bash

# We are guessing that whoever owns PulseAudio owns the display
xuser=$(stat -c %U /proc/"$(pgrep -f pulseaudio)")
echo "My steam-os: $xuser is the user we are going to use"

case $1 in
	pre)
		# We assume that Alt-O is a keybind for setting the monitors down to a single HDMI input
		sudo -u "$xuser" bash -c "export DISPLAY=:0 ; xdotool keydown Alt key o keyup Alt"

		killall steam

		# We wait for Steam to go away
		# Try 5 times, since we might be waiting for cloud sync
		for i in $(seq 1 5)
		do
			if pgrep -f steam.sh > /dev/null
			then
				sleep 2
				echo "My steam-os: $i time waiting for Steam to shutdown"
			fi
		done

		sleep 1

		killall -9 steam
		;;
	post)
		# If we don't sleep, things go wrong sometimes
		# I wish I had a better way of doing this
		sleep 3

		# We assume that Alt-S is a keybind for launching Steam
		sudo -u "$xuser" bash -c "export DISPLAY=:0 ; xdotool keydown Alt key s keyup Alt"
		;;
esac
